import { Layout } from "@/components/Layout";
import { AuthContext } from "@/context/AuthContext";
import { verifyToken } from "@/lib/userLogin";
import { getCookie } from "cookies-next";
import Head from "next/head";
import { useContext, useState } from "react";

export default function AddNewRepo() {

  const {user} = useContext(AuthContext)

  const [repository, setRepository] = useState({
    link: "",
    inputRadio: ""
  });

  const onChangeInput = (e) =>
    setRepository({ ...repository, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    const {link} = repository;
    const {username} = user;
    if(repository.inputRadio === "private"){
      // console.log("private", user.privateKey)
      // try{
      //   const response = await fetch("http://localhost:3000/api/private", {
      //     method: "POST",
      //     headers: {"Content-Type":"application/json"},
      //     body: JSON.stringify({username, link})
      //   })
      // }catch(err){
      //   console.log(err)
      // }
    }else{
      // console.log("public", user.userKey)
      try{
        const response = await fetch("http://localhost:3000/api/public", {
          method: "POST",
          headers: {"Content-Type":"application/json"},
          body: JSON.stringify({username, link})
        })
      }catch(err){
        console.log(err)
      }
    }
  };

  return (
    <>
      <Head>
        <title>Novo repositório</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="form-new-repo">
          <form onSubmit={handleSubmit}>
            <input
              type="text"
              placeholder="Adicionar repositório:"
              name="link"
              value={repository.link}
              onChange={onChangeInput}
            />
            <fieldset>
              <div>
                <label>
                  <input
                    type="radio"
                    name="inputRadio"
                    id="public-radio"
                    value={"public"}
                    checked={repository.inputRadio === "public"}
                    onChange={onChangeInput}
                  />
                  Público
                </label>
              </div>
              <div>
                <label>
                  <input
                    type="radio"
                    name="inputRadio"
                    id="private-radio"
                    value={"private"}
                    checked={repository.inputRadio === "private"}
                    onChange={onChangeInput}
                  />
                  Privado
                </label>
              </div>
            </fieldset>
            <input type="submit" />
          </form>
        </div>
      </Layout>
    </>
  );
}

export const getServerSideProps = async ({ req, res }) => {
  try {
    const token = getCookie("authorization", { req, res });
    if (!token) throw new Error("Token inválido");
    verifyToken(token);
    return {
      props: {},
    };
  } catch (err) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
      props: {},
    };
  }
};
