import { Layout } from "@/components/Layout";
import Head from "next/head";

export default function Login() {
  return (
    <>
      <Head>
        <title>Página de login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="form-login">
          <form>
            <input type="text" placeholder="Username:" />
            <input type="password" placeholder="Senha" />
          </form>
        </div>
      </Layout>
    </>
  );
}
