import { Layout } from "@/components/Layout";
import Head from "next/head";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Página inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex-profile">
        <img src="https://github.com/heitor2002.png" alt="" />
        <div className="data-profile">
            <ul>
                <li>Username: ...</li>
                <li>Email: ...</li>
                <li>Repositórios: ...</li>
            </ul>
        </div>
        </div>
      </Layout>
    </>
  );
}
