import { Layout } from "@/components/Layout";
import Head from "next/head";

export default function Register() {
    return (
        <>
        <Head>
        <title>Página de registro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>

        </Layout>
        </>
    )
}