import { Layout } from "@/components/Layout";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Register() {
  const [user, setUser] = useState({
    username: "",
    email: "",
    password: "",
    userKey: "",
    privateKey: "",
  })
  return (
    <>
      <Head>
        <title>Página de registro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="form-login">
          <form>
            <input type="text" placeholder="Usuário github:" />
            <input type="text" placeholder="E-mail:" />
            <input type="text" placeholder="Confirmar e-mail:" />
            <input type="password" placeholder="Senha:" />
            <input type="password" placeholder="Confirmar senha:" />
            <p>
              Já possui conta?{" "}
              <Link href={"/login"}>Faça seu login aqui!</Link>
            </p>
            <input type="submit" value={"Cadastrar"} />
          </form>
        </div>
      </Layout>
    </>
  );
}
